# docker-compose.yml
version: '3.8'

services:
  # The React Frontend Application
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Access the app at http://localhost:8080
    container_name: household-harmony-hub-frontend
    restart: unless-stopped
    # This frontend needs to know where the backend API is.
    # You would build a backend service (e.g., in Node.js/Python)
    # that connects to the 'db' service below.
    # environment:
    #   - REACT_APP_API_URL=http://backend:3001 

  # The PostgreSQL Database
  db:
    image: postgres:14-alpine
    container_name: household-harmony-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: household_user
      POSTGRES_PASSWORD: a_strong_password_here
      POSTGRES_DB: household_db
    ports:
      # Expose the DB port only if you need to connect from your host machine
      - "5432:5432" 
    volumes:
      # This persists the database data on your host machine
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
